# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7144b815331be7ef8f9457216353057409bbdbd1d0eccadb41b39120b4088edb3c5ee5a0312499dc69e6e19db8e1f2910bfae00db0348d250d777c5d0ae85190

test:
  secret_key_base: a19051e617443156c802935c684a559887cae6b9c9f36de563c5491f27e2eee44576946a400cb18bb504894f0d77ca7321d376af9a9806973b7aed5734e121e6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
